- name: Ensure Movim root directory exists with proper permissions
  file:
    path: "{{ movim_dir }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0755'

- name: Ensure Movim cache directory exists
  file:
    path: "{{ movim_dir }}/cache"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0755'

- name: Ensure Movim log directory exists
  file:
    path: "{{ movim_dir }}/log"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0755'

- name: Ensure Movim public/cache directory exists
  file:
    path: "{{ movim_dir }}/public/cache"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0755'
